### ISSUE TITLE
format specific line ranges

### ISSUE THREAD

**Issue by kylepink** [sp0/rustfmt#17]
There should be an option to format or issue replacements for specific lines or line ranges.

**Possible behaviour:**
* A flag of --lines=&lt;string&gt;, where &lt;string&gt; is &lt;start_line&gt;:&lt;end_line&gt;.
* Ranges should be 1-based of uint type.
* Ranges should be inclusive. ie, --lines=1:1 = first line only.  --lines=2:4 = 2nd, 3rd and 4th lines.
* Multiple line ranges should be possible. Multiple instances of the flag should be specified in the command.
* Can not work with multiple files.

The behaviour above would make it just like clang format.

**Comment by madmalik** [comment]
I can see the need for an option like this. Especially in (complex) macro invocations all bets are off. 
But i would suggest annotation in the source code. 

For example:
```
fn main() {
    use std::fmt::Write;
    let mut out = String::new();

    //"
    write_html!(&mut out,
      html[
        head[title["Macros guide"]]
        body[h1["Macros are the best!"]]
      ]);
    //"
    assert_eq!(out,
        "<html><head><title>Macros guide</title></head>\
         <body><h1>Macros are the best!</h1></body></html>");
}
```

**Comment by kamalmarhubi** [comment]
Cool! I just came to be sure that this feature was added or was being thought about.

Some minor bikeshedding:
- Would you consider hyphen instead of colon for the separator? Colon is more often used to separate line:col.
- Would you consider a comma separated list in addition or instead of specifying the flag repeatedly? I'm thinking of scripting a pre-commit hook. Scripting something like (in Python) `",".join("%d-%d" % (start, end) for start, end in ranges)` is a bit more straightforward.

I'd be happy to supply patches.

**Comment by sp0** [comment]
I'm not sure if you getting this project confused with the other rustfmt project (https://github.com/nrc/rustfmt/). I just renamed this project to avoid confusion.

Anyway I would agree with you on both points. If you wish, you can go ahead and change it. I would be happy to accept any pull requests.

**Comment by kamalmarhubi** [comment]
The feature is useful enough that whichever rustfmt prevails, I think any and all should support it well. :-)
